/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:943a04f8-4936-4a0d-90ae-63835b038ccc",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_T60O4CqA0",
    "aws_user_pools_web_client_id": "28psvcjnaiatcq8j0n1dqhppcq",
    "oauth": {
        "domain": "ngxchessboardmaster224a1400-224a1400-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/,https://main.dcqz9z6e2g1g2.amplifyapp.com/",
        "redirectSignOut": "http://localhost:4200/,https://main.dcqz9z6e2g1g2.amplifyapp.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
